shannblog/blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
	url(u'^$', views.IndexView.as_view(), name='index'),
	url(u'^index/', views.IndexView.as_view(), name='index'),
	url(u'^post/(?P<pk>[0-9]+)/$', views.BlogDetailView.as_view(), name='detail'),
	url(u'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
	url(u'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
	# url(u'^search/$', views.search, name='search')
]

shannblog/comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
	url(u'^comment/post/(?P<blog_pk>[0-9]+)/$', views.blogcomments, name='blogcomments'),
	]

shannblog/shannblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^ckeditor', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shannblog/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.html import strip_tags
import markdown
from ckeditor_uploader.fields import RichTextUploadingField
from readcount.models import ReadNumExpandMethod

# Create your models here.

class Author(models.Model):
	"""docstring for Author"""
	#博客作者模型
	name = models.CharField(max_length=20)
	email = models.EmailField()
	descript = models.TextField()

	def __str__(self):
		return self.name

class Tag(models.Model):
	"""docstring for Tag"""
	#标签模型
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

class Category(models.Model):
	"""docstring for ClassName"""
	#分类模型
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name
		
class Blog(models.Model, ReadNumExpandMethod):
	"""docstring for Blog"""
	#博客模型
	caption = models.CharField(max_length=50)
	content = RichTextUploadingField()
	excerpt = models.CharField(max_length=50, blank=True)
	creattime = models.DateTimeField(auto_now_add=True)	#日期，新增自动写入
	modifiedtime = models.DateTimeField(auto_now=True)	#日期，修改自动更新
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	author = models.ForeignKey(Author, on_delete=models.CASCADE)	
	tag = models.ManyToManyField(Tag, blank=True)

	def __str__(self):
		return self.caption

	def get_absolute_url(self):
		return reverse('blog:detail', kwargs={'pk':self.pk})

	def save(self, *args, **kwargs):
		if not self.excerpt:
			md = markdown.Markdown(extensions=[
				 'markdown.extensions.extra',
				 'markdown.extensions.codehilite',
				 ])
			self.excerpt = strip_tags(md.convert(self.content))[:50]
		super(Blog, self).save(*args, **kwargs)
		
	class Meta:
		ordering = ['-creattime']

shannblog/comments/models.py
from django.db import models

# Create your models here.

class Comments(models.Model):
	"""docstring for Comments"""
	name = models.CharField(max_length=100)
	email = models.EmailField(max_length=255)
	url = models.URLField(blank=True)
	text = models.TextField()
	creattime = models.DateTimeField(auto_now_add=True)
	blog = models.ForeignKey('blog.Blog', on_delete=models.CASCADE)

	def __str__(self):
		return self.text[:20]

shannblog/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import ListView, DetailView
from django.contrib.contenttypes.models import ContentType
from .models import Blog, Category, Tag
import markdown
from comments.forms import CommentsForm
from django.db.models import Q
from readcount.models import ReadNum
from readcount.utils import readcount_once_read 
# Create your views here.

# def index(request):
# 	postlist = Blog.objects.all().order_by('-creattime')
# 	return render(request, 'blog/index.html', context={
# 		'postlist':postlist,
# 		})

class IndexView(ListView):
	"""docstring for IndexView"""
	model = Blog
	template_name = 'blog/index.html'
	context_object_name = 'postlist'
	paginate_by = 2

# def detail(request, pk):
# 	post = get_object_or_404(Blog, pk=pk)
# 	post.increase_views()
# 	post.content = markdown.markdown(post.content,
# 									extensions=[
# 									'markdown.extensions.extra',
# 									'markdown.extensions.codehilite',
# 									'markdown.extensions.toc',
# 									])
# 	form = CommentsForm()
# 	commentlist = post.comments_set.all()
# 	return render(request, 'blog/detail.html', context={
# 		'post':post,
# 		'form':form,
# 		'commentlist':commentlist,
# 		})

class BlogDetailView(DetailView):
	"""docstring for BlogDetailView"""
	model = Blog
	template_name = 'blog/detail.html'
	context_object_name = 'post'

	def get(self, request, *args, **kwargs):
		response = super(BlogDetailView, self).get(request, *args, **kwargs)
		read_cookie_key = readcount_once_read(self, request, self.object)
		response.set_cookie(read_cookie_key, True)	#阅读cookie标记
		return response

	def get_object(self, queryset=None):
		post = super(BlogDetailView, self).get_object(queryset=None)
		post.content = markdown.markdown(post.content,
										extensions=[
										'markdown.extensions.extra',
										'markdown.extensions.codehilite',
										'markdown.extensions.toc',
										])
		return post

	def get_context_data(self, **kwargs):
		context = super(BlogDetailView, self).get_context_data(**kwargs)
		form = CommentsForm()
		commentlist = self.object.comments_set.all()
		context.update({
			'form':form,
			'commentlist':commentlist,
			})		
		return context

# def category(request, pk):
# 	cate = get_object_or_404(Category, pk=pk)
# 	postlist = Blog.objects.filter(category=cate).order_by('-creattime')
# 	return render(request, 'blog/index.html', context={
# 		'postlist':postlist,
# 		})

class CategoryView(IndexView):
	"""docstring for ClassName"""
	def get_queryset(self):
		cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
		return super(CategoryView, self).get_queryset().filter(category=cate)

class TagView(IndexView):
	"""docstring for TagView"""
	def get_queryset(self):
		tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
		return super(TagView, self).get_queryset().filter(tag=tag)

def search(request):
	q = request.GET.get('query')
	errormsg = ''
	if not q:
		errormsg = '请输入关键词'
		return render(request, 'blog/index.html', context={
			'errormsg':errormsg,
			})
	postlist = Blog.objects.filter(Q(caption__icontains=q) | Q(content__icontains=q))
	return render(request, 'blog/index.html', context={
		'postlist':postlist,
		'errormsg':errormsg,
		})

shannblog/templates/blog/detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}
				<!-- Main -->
					<div id="main">

						<article class="post">
								<header>
									<div class="title">
										<h2>{{ post.caption }}</h2>
										<!-- <p><a href="{% url 'blog:category' post.category.pk %}">{{ post.category }}</a></p> -->
										<div class="widget widget-tag-cloud">
					                    <ul>
					                    	{% for tag in post.tag.all %}
					                        <li>
					                            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
					                        </li>
					                        {% empty %}
					                        {% endfor%}
					                    </ul>
			              		  </div>
									</div>
									<div class="meta">
										<time class="published" datetime="2015-10-18">{{ post.creattime|date:"Y-m-d H:i" }}</time>
										<a href="#" class="author"><span class="name">{{ post.author }}</span><img src="{% static 'blog/images/avatar.jpg'%}" alt="" /></a>
									</div>
								</header>

								<section>
									<p>{{ post.content|safe }}</p>
								</section>
								<footer>
									<ul class="stats">
										<li><a href="{% url 'blog:category' post.category.pk %}">{{ post.category }}</a></li>
										<li>{{ post.get_readnum }} 阅读</li>
										<li><a href="#" class="icon fa-comment">{{ post.comments_set.count }}</a></li>
									</ul>
								</footer>
						</article>

						<article class="post">
						<form method="post" action="{% url 'comments:blogcomments' post.pk %}">
										{% csrf_token %}
										<div class="row uniform">
											<div class="6u 12u$(xsmall)">
												<label for="{{ form.name.id_for_label }}">名字：</label>
											    {{ form.name }}
											    {{ form.name.errors }}
											</div>
											<div class="6u$ 12u$(xsmall)">
												<label for="{{ form.email.id_for_label }}">邮箱：</label>
												{{ form.email }}
												{{ form.email.errors }}
											</div>
											<div class="6u$ 12u$(xsmall)">
												<label for="{{ form.email.id_for_label }}">URL：</label>
												{{ form.url }}
												{{ form.url.errors }}
											</div>
											<div class="12u$">
												<label for="{{ form.email.id_for_label }}">评论：</label>
												{{ form.text }}
												{{ form.text.errors }}
											</div>
											<ul class="actions">
												<li><input class="button big fit" type="submit" value="发表评论" /></li>
											</ul>
										</div>
						</form>
						 <aside class="comments" id="comments">
		                        <hr>

		                        <h2><i class="fa fa-comments"></i>{{ post.comments_set.count }}Comments</h2>
								{% for comment in commentlist %}
		                        <article class="comment">
		                            <header class="clearfix">
		                                <img src="{% static 'blog/images/logo.jpg'%}" alt="A Smart Guy" class="avatar">
		                                <div class="meta">
		                                    <h3><a href="#">{{ comment.name }}</a></h3>
		                                    <span class="date">
		                                        {{ comment.creattime|date:"Y-m-d H:i" }}
		                                    </span>
		                                    <span class="separator">
		                                        -
		                                    </span>
		                                    
		                                    <a href="#create-comment" class="reply-link">Reply</a>                
		                                </div>
		                            </header>
		                             <div class="body">
		                              {{ comment.text }}
		                            </div>
		                        </article>
								{% empty %}
								<h2>还没有任何评论</h2>
								{% endfor %}
		                       <!--  <article class="comment reply">
		                            <header class="clearfix">
		                                <img src="{% static 'blog/images/logo.jpg'%}" alt="A Smart Guy" class="avatar">
		                                <div class="meta">
		                                    <h3><a href="#">John Doe</a></h3>
		                                    <span class="date">
		                                        24 August 2015
		                                    </span>
		                                    <span class="separator">
		                                        -
		                                    </span>
		                                    
		                                    <a href="#create-comment" class="reply-link">Reply</a>                
		                                </div>
		                            </header>
		                             <div class="body">
		                               Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere sit perspiciatis debitis, vel ducimus praesentium expedita, assumenda ipsum cum corrupti dolorum modi. Rem ipsam similique sapiente obcaecati tenetur beatae voluptatibus.
		                            </div>
		                        </article> -->
                    	</aside>
					</article>
					
			</div>
{% endblock main %}

shannblog/templates/blog/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load blog_tags %}

{% block main %}
					<div id="main">
						{% if errormsg %}
						<p>{{ errormsg }}</p>
						{% endif %}
						<!-- Post -->
						{% for post in postlist %}
							<article class="post">
								<header>
									<div class="title">
										<h2><a href="{{ post.get_absolute_url }}">{{ post.caption }}</a></h2>
										<div class="widget widget-tag-cloud">
						                    <ul>
						                    	{% for tag in post.tag.all %}
						                        <li>
						                            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
						                        </li>
						                        {% empty %}
						                        {% endfor%}
						                    </ul>
						                </div>
									</div>
									<div class="meta">
										<time class="published" datetime="{{ post.creattime|date:'Y-m-d H:i' }}">{{ post.creattime|date:"Y-m-d H:i" }}</time>
										<a href="#" class="author"><span class="name">{{ post.author }}</span><img src="{% static 'blog/images/logo.jpg' %}" alt="" /></a>
									</div>
								</header>
								<a href="{{ post.get_absolute_url }}" class="image featured"><img src="{% static 'blog/images/pic03.jpg' %}" alt="" /></a>
								<p>{{ post.excerpt }}</p>
								<footer>
									<ul class="actions">
										<li><a href="{{ post.get_absolute_url }}" class="button big">Continue Reading</a></li>
									</ul>
									<ul class="stats">
										<li><a href="{% url 'blog:category' post.category.pk %}">{{ post.category }}</a></li>
										<li>{{ post.get_readnum }} 阅读</li>
										<li><a href="#" class="icon fa-comment">{{ post.comments_set.count }}</a></li>
									</ul>
								</footer>
							</article>
						{% empty %}
  							<div class="no-post"><h2>暂时还没有发布的文章！</h2></div>
						{% endfor %}

						<!-- Pagination -->
							{% if is_paginated %}
							<ul class="actions pagination">
								{% if page_obj.has_previous %}
								<li><a href="?page={{ page_obj.previous_page_number }}" class="button big previous">上一页</a></li>
								{% else %}
								<li><a href="#" class="disabled button big previous">上一页</a></li>
								{% endif %}
								{% if page_obj.has_next %}
								<li><a href="?page={{ page_obj.next_page_number }}" class="button big next">下一页</a></li>
								{% else %}
								<li><a href="#" class="disabled button big next">下一页</a></li>		
								{% endif %}
							</ul>
							{% endif %}

						</div>

				<!-- Sidebar -->
					<section id="sidebar">

						<!-- Intro -->
							<section id="intro">
								 <div class="logo-inner text-center">
		                            <div class="logo-name">
		                                <a href="index.html">
		                                    <img src="{% static 'blog/images/logo.jpg' %}" class="img-circle" />
		                                </a>
		                            </div>
                       			 </div>
								<header>
									<h2>Shann</h2>
									<p>God said, Let there be light: and there was light.</p>
								</header>
							</section>

						<!-- Rencent Posts -->
							<section>
								<div class="mini-posts">

									<!-- Rencent Post -->
										{% getrecentblogs as recentblogslist %}
										{% for blog in recentblogslist %}
											<article class="mini-post">
												<header>
													<h3><a href="{% url 'blog:detail' blog.pk %}">{{ blog.caption }}</a></h3>
													<time class="published" datetime="2015-10-20">{{ blog.creattime|date:"Y-m-d H:i" }}</time>
													<a href="#" class="author"><img src="{% static 'blog/images/logo.jpg' %}" alt="" /></a>
												</header>
												<a href="{% url 'blog:detail' blog.pk %}" class="image"><img src="{% static 'blog/images/pic03.jpg' %}" alt="" /></a>
											</article>
										{% empty %}
										暂无文章！
										{% endfor %}

								</div>
							</section>

						<!-- Catetory List -->
						<!-- <SCRIPT language=JavaScript>function MM_jumpMenu(targ,selObj,restore){  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");  if (restore) selObj.selectedIndex=0;}</SCRIPT>
							<section>
								<h2>分类</h2>
								<div class="select-wrapper">
									<select name="demo-category" id="demo-category" onchange="MM_jumpMenu('parent',this,0)">
										<OPTION selected>文章分类</OPTION> 
										{% getcategory as categoryslist %}
										{% for category in categoryslist %}
											<option value="{% url 'blog:category' category.pk %}">{{ category.name }}</option>
										{% empty %}
										暂无分类！
										{% endfor %}
									</select>
								</div>
							</section> -->
							<section>
								<ul class="posts">
										<li>
											<article>
												<header>
													<h2>分类</h2>
													{% getcategory as categoryslist %}
													{% for category in categoryslist %}
													<h3><a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.numblogs }})</span></a></h3>
													{% empty %}
													暂无分类！
													{% endfor %}
												</header>
											</article>
										</li>
								</ul>
							</section>

						<!-- Tags -->
							<div class="widget widget-tag-cloud">
			                   <h2>标签云</h2>
			                   {% gettags as tagslist %}
			                    <ul>
			                    	{% for tag in tagslist %}
			                        <li>
			                            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
			                        </li>
			                        {% empty %}
			                        暂无标签！
			                        {% endfor%}
			                    </ul>
			                </div>

					</section>
{% endblock main %}
							